[package]
name = "ziondefi"
version = "0.1.0"
authors = ["Adeyeye George David"]
description = ""
edition = "2024_07"
cairo-version = "2.8.0"
license = "MIT"

[dependencies]
starknet = "2.8.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma.git", branch = "main" }

[dev-dependencies]
cairo_test = "2.12.2"

[[target.starknet-contract]]
sierra = true
casm = true
